config/routes.rb
PixelsDoc::Application.routes.draw do
  root to: 'documentation#home'

  devise_for :users

  resources :categories, only: [:show, :edit, :create, :update]
  resources :functions, only: [:show, :edit, :create, :new, :update]

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :functions

  validates :name, presence: true
end

app/models/function.rb
# == Schema Information
#
# Table name: functions
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  category_id :integer
#  description :string(255)
#  content     :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Function < ActiveRecord::Base
  attr_accessible :category_id, :content, :description, :name
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :content, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < CommonController
  before_filter :signed_in_user, only: [:create]
  before_filter :sidebar_data, except: [:create]

  def index
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @cat = Category.new(params[:category])
    if @cat.save
      redirect_to root_url
    else
      flash.now[:error] = "Category invalid. Please try again."
      redirect_to root_url
    end
  end
end

app/controllers/common_controller.rb
class CommonController < ApplicationController

  private
    def signed_in_user
      redirect_to user_session_path, notice: "Please sing in." unless user_signed_in?
    end

    def sidebar_data
      @categories = Category.order("name")
      @functions = Function.order("name")
      @new_category = Category.new
    end
end

app/controllers/documentation_controller.rb
class DocumentationController < CommonController
  before_filter :sidebar_data

  def home
  end
end

app/controllers/functions_controller.rb
class FunctionsController < CommonController
  before_filter :signed_in_user, only: [:edit, :new, :create, :update]
  before_filter :sidebar_data, except: [:create]

  def show
    @function = Function.find(params[:id])
  end

  def edit
    @function = Function.find(params[:id])
  end

  def new
    @function = Function.new
  end

  def create
    @function = Function.new(params[:function])
    if @function.save
      flash.now[:success] = "New function created: #{@function.name}"
      redirect_to @function
    else
      render 'new'
    end
  end

  def update
    @function = Function.find(params[:id])
    if @function.update_attributes(params[:function])
      flash.now[:success] = "#{@function.name} updated!"
      redirect_to @function
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Return the full title on a per-page basis
  def full_title(page_title)
    base_title = "PixelsDoc"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/documentation_helper.rb
module DocumentationHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

end

app/views/categories/show.html.haml
%h1= @category.name
%ul
  - @category.functions.each do |f|
    %li
      = link_to f.name, f

app/views/documentation/home.html.haml
%h1= "Pixels Framework Documentation"
%p{style: "white-space: pre-wrap"}
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec elit mauris, porta tincidunt orci. Mauris ullamcorper urna mollis mi vestibulum bibendum. Integer ullamcorper, enim vel tristique convallis, erat justo eleifend ante, fermentum varius nulla tortor a dolor. Pellentesque aliquam sem pulvinar orci mattis lobortis. Proin ut sem volutpat quam elementum facilisis in feugiat eros. Ut non sapien at odio pretium fringilla fringilla a magna. Morbi faucibus sollicitudin commodo. Cras blandit egestas quam, et euismod metus venenatis vitae. Aenean at lorem a diam aliquet iaculis. Integer a odio at erat ornare porta.
  %br
  In consectetur quam et ante commodo vel bibendum ipsum ornare. Aliquam erat volutpat. Vestibulum diam dolor, hendrerit tristique condimentum eu, condimentum quis magna. Ut a enim enim. Curabitur tellus nisi, molestie vel blandit ut, placerat eu augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis bibendum, nisl sed iaculis lobortis, odio lectus ultrices libero, ut sollicitudin augue tortor quis nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In quis risus mi. Praesent ante odio, commodo et lobortis nec, vehicula quis mi. Etiam sodales tellus volutpat massa ultricies ullamcorper. Donec mattis vestibulum urna, sed suscipit ligula dictum a. Mauris ut augue nec augue ullamcorper consectetur. Suspendisse in euismod mauris. Nunc faucibus bibendum urna vel commodo. Donec non ultrices mi.
  %br
  Suspendisse sed pretium sapien. Praesent sit amet massa nisi, sit amet molestie justo. Donec a metus et sem posuere blandit non non purus. Sed tempus lobortis vehicula. Morbi iaculis lectus vitae erat luctus consequat. Mauris eget magna nec felis faucibus dignissim. Sed dictum elementum ornare. Vestibulum aliquet diam ut leo dignissim quis feugiat leo ultricies. Aliquam non dui quis erat placerat vulputate sit amet et arcu. Aenean sit amet fermentum neque. Morbi viverra est tellus, vel vulputate velit.
  %br
  Fusce a bibendum augue. Aenean gravida nisl quis arcu malesuada porta. Aliquam ut facilisis ante. Aenean risus dolor, consequat volutpat pulvinar eu, feugiat ac massa. Duis facilisis nisi in nibh malesuada malesuada. Quisque sem leo, porta sed molestie faucibus, egestas sed diam. Proin eu eros metus. Integer faucibus pretium massa, at mattis nisl posuere vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris blandit sapien at libero aliquet semper. Aenean nec massa tellus, sed tincidunt odio. Ut eu justo in ligula commodo molestie.
  %br
  Integer ullamcorper accumsan sem, ut fermentum lorem ultrices vel. Maecenas ut quam id mi tincidunt scelerisque. Suspendisse erat ligula, hendrerit vitae ornare sollicitudin, euismod at nisl. Sed et quam nisi. Donec a elit ligula, eu viverra sapien. Quisque tortor sem, ultricies ut vulputate eu, lacinia feugiat magna. Donec vel velit vel dui vulputate vehicula id eu dui. Fusce nec pretium metus. Nullam interdum, massa vitae commodo volutpat, urna dolor luctus metus, et ultricies ipsum lorem non magna.

app/views/functions/edit.html.haml
%h1= "Editing #{@function.name}"
= form_for @function, html: { id: "function_form" } do |f|
  = render 'shared/function_error_messages'
  = f.text_field :name, placeholder: "Function name...", class: "column6"
  = f.collection_select :category_id, Category.order("name"), :id, :name, {}, {class: 'column6'}
  = f.text_field :description, placeholder: "Enter a short description here...", class: "column12"
  = f.label :content
  #epiceditor.mb20{style: "height: 400px"}
  .hide
    = f.text_area :content, class: "column12"
  = f.submit "Post", class: "btn block action"

- javascript_include_tag "tj_epiceditor"

app/views/functions/new.html.haml
%h1= "New Function"
= form_for @function, html: { id: "function_form" } do |f|
  = render 'shared/function_error_messages'
  = f.text_field :name, placeholder: "Function name...", class: "column6"
  = f.collection_select :category_id, Category.order("name"), :id, :name, {}, {class: 'column6'}
  = f.text_field :description, placeholder: "Enter a short description here...", class: "column12"
  = f.label :content
  #epiceditor.mb20{style: "height: 400px"}
  .hide
    = f.text_area :content, class: "column12"
  = f.submit "Post", class: "btn block action"

- javascript_include_tag "tj_epiceditor"

app/views/functions/show.html.haml
- provide(:title, @function.name)
%h1
  #{@function.name}
  - if user_signed_in?
    %small
      = link_to "Edit", edit_function_path(@function)

%p
  - if @function.category
    %strong
      Category:
    = link_to @function.category.name, @function.category
    %br
  %strong
    Description:
  #{@function.description}
%hr
.info
  = markdown @function.content

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render "shared/shim"

  %body
    - unless @hide_nav_bar
      = render "shared/nav_bar"

    .wrapper.mt50
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      .container-fluid
        - if @categories and @functions
          .column3
            = render "shared/side_bar"
        .column9
          = yield

app/views/shared/_function_error_messages.html.haml
- if @function.errors.any?
  #error_explanation
  .alert.alert-error
    The form contains #{pluralize(@function.errors.count, "error")}.
  %ul
    - @function.errors.full_messages.each do |msg|
      %li
        * #{msg}

app/views/shared/_nav_bar.html.haml
#headernavbar.header.navbar.fixed-top
  .headerwrap.navbar-wrap
    .wrap.wrapper.pt5.flush
      #left_header.left
        = link_to "PixelsDoc", root_url, class: "mt5", style: "font-size: 25px; color: #FFF; display: inline-block;"
      #right_header.right
        - if user_signed_in?
          =link_to '/admin' do
            %span{style: "color: white;"}= current_user.email
            = gravatar_for current_user, size: 30
        - else
          = link_to "Sign In", user_session_path, class: "btn small"

app/views/shared/_shim.html.haml
<!--[if lt IE 9]>
%script{ src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}
<![endif]-->

app/views/shared/_side_bar.html.haml
%h2
  Categories
  - if user_signed_in?
    %small
      %a#show_new{href: '#'}= "New"
- if user_signed_in? and @new_category
  = form_for @new_category, html: { id: "new_category_form", class: "hide" } do |f|
    = f.text_field :name, placeholder: "New Category...", class: "block"
    = f.submit "Post", class: "btn block action"
- @categories.each do |cat|
  .block
    = link_to cat.name, cat
%h2
  Functions
  - if user_signed_in?
    %small
      = link_to "New", new_function_path
- @functions.each do |f|
  .block
    = link_to f.name, f

:javascript
  $('#show_new').click(function(e){
    e.preventDefault();
    $('#new_category_form').fadeIn();
  });